name: Build Pre-build Packages for Linux

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  build:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmkl-dev
    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: NPM Install
      run: npm ci --ignore-scripts
    - name: Build & test
      run:  |
        export MKLROOT=/opt/intel/mkl
        npm run build:test
    - name: Build Release
      run: |
        export MKLROOT=/opt/intel/mkl
        npm run prebuild-package -- --all
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: prebuilds/*.tar.gz
        tag_name: 'v0.2.2-alpha.0'
