name: Build Pre-build Packages for Alpine

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Prepare Image
      run: docker build -f Dockerfile.build -t faiss-build-alpine .
    - name: Build & test
      run: docker run --rm faiss-build-alpine
    - name: Build Release
      run: docker run --rm -v $(pwd)/prebuilds:/app/prebuilds faiss-build-alpine run prebuild-package -- --all
    - name: Get Version
      id: version
      run : |
        VERSION=$(node -p -e "require('./package.json').version")
        echo $VERSION
        echo VERSION=$VERSION >> "$GITHUB_OUTPUT"
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: prebuilds/*.tar.gz
        tag_name: "v${{ steps.version.outputs.VERSION }}"
